"""added subject in grade

Revision ID: ff769a1bccb7
Revises: 0b0f3e134821
Create Date: 2018-12-01 22:49:27.260468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff769a1bccb7'
down_revision = '0b0f3e134821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('subject', sa.String(), nullable=True))
    op.create_index(op.f('ix_grade_subject'), 'grade', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_subject'), table_name='grade')
    op.drop_column('grade', 'subject')
    # ### end Alembic commands ###
